/*
*Hailstone array
*/

#include <stdio.h>

#define ITEMPERLINE 6       //item per line

int hailstone(int n);

int main(int argc, char const *argv[]) {
    int n = 0;
    scanf("%d", &n);
    printf("Hailstone generated by %d:\n", n);
    printf("%5d", n);
    int itemCount = 1;      //how many numbers generated in the array
    while((n = hailstone(n))){      //the paratheses are to get rid of the warning
        printf("%5d", n);
        if(++itemCount % ITEMPERLINE == 0){
            putchar('\n');
        }
    }
    printf("\nNumber of hailstone generated: %d\n", itemCount);
    return 0;
}

int hailstone(int n){
    int rtn = 0;
    if(n == 1){
        rtn = 0;
    }
    else if(n % 2 == 0){
        rtn = n / 2;
    }
    else{
        rtn = 3 * n + 1;
    }

    return rtn;
}
